//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevletVergiSistemi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VergiSistemiEntities : DbContext
    {
        public VergiSistemiEntities()
            : base("name=VergiSistemiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bakanliklar> Bakanliklars { get; set; }
        public virtual DbSet<Borclar> Borclars { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Vatandaslar> Vatandaslars { get; set; }
        public virtual DbSet<Vergiler> Vergilers { get; set; }
    
        public virtual int bakanlikEkle(string bakanlikAd, string daireBaskanlik, Nullable<int> ciro, string merkez)
        {
            var bakanlikAdParameter = bakanlikAd != null ?
                new ObjectParameter("bakanlikAd", bakanlikAd) :
                new ObjectParameter("bakanlikAd", typeof(string));
    
            var daireBaskanlikParameter = daireBaskanlik != null ?
                new ObjectParameter("daireBaskanlik", daireBaskanlik) :
                new ObjectParameter("daireBaskanlik", typeof(string));
    
            var ciroParameter = ciro.HasValue ?
                new ObjectParameter("ciro", ciro) :
                new ObjectParameter("ciro", typeof(int));
    
            var merkezParameter = merkez != null ?
                new ObjectParameter("merkez", merkez) :
                new ObjectParameter("merkez", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("bakanlikEkle", bakanlikAdParameter, daireBaskanlikParameter, ciroParameter, merkezParameter);
        }
    
        public virtual int bakanlikGüncelle(Nullable<int> bakanlikId, string bakanlikAd, string daireBaskanlik, Nullable<int> ciro, string merkez)
        {
            var bakanlikIdParameter = bakanlikId.HasValue ?
                new ObjectParameter("bakanlikId", bakanlikId) :
                new ObjectParameter("bakanlikId", typeof(int));
    
            var bakanlikAdParameter = bakanlikAd != null ?
                new ObjectParameter("bakanlikAd", bakanlikAd) :
                new ObjectParameter("bakanlikAd", typeof(string));
    
            var daireBaskanlikParameter = daireBaskanlik != null ?
                new ObjectParameter("daireBaskanlik", daireBaskanlik) :
                new ObjectParameter("daireBaskanlik", typeof(string));
    
            var ciroParameter = ciro.HasValue ?
                new ObjectParameter("ciro", ciro) :
                new ObjectParameter("ciro", typeof(int));
    
            var merkezParameter = merkez != null ?
                new ObjectParameter("merkez", merkez) :
                new ObjectParameter("merkez", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("bakanlikGüncelle", bakanlikIdParameter, bakanlikAdParameter, daireBaskanlikParameter, ciroParameter, merkezParameter);
        }
    
        public virtual ObjectResult<bakanlikListele_Result> bakanlikListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bakanlikListele_Result>("bakanlikListele");
        }
    
        public virtual int bakanlikSil(Nullable<int> bakanlikId)
        {
            var bakanlikIdParameter = bakanlikId.HasValue ?
                new ObjectParameter("bakanlikId", bakanlikId) :
                new ObjectParameter("bakanlikId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("bakanlikSil", bakanlikIdParameter);
        }
    
        public virtual int borcEkle(string borcAdi, string borcDurumu, Nullable<int> borcTutari, Nullable<System.DateTime> borcTarihi, Nullable<int> vergiId, Nullable<int> kisiNo)
        {
            var borcAdiParameter = borcAdi != null ?
                new ObjectParameter("borcAdi", borcAdi) :
                new ObjectParameter("borcAdi", typeof(string));
    
            var borcDurumuParameter = borcDurumu != null ?
                new ObjectParameter("borcDurumu", borcDurumu) :
                new ObjectParameter("borcDurumu", typeof(string));
    
            var borcTutariParameter = borcTutari.HasValue ?
                new ObjectParameter("borcTutari", borcTutari) :
                new ObjectParameter("borcTutari", typeof(int));
    
            var borcTarihiParameter = borcTarihi.HasValue ?
                new ObjectParameter("borcTarihi", borcTarihi) :
                new ObjectParameter("borcTarihi", typeof(System.DateTime));
    
            var vergiIdParameter = vergiId.HasValue ?
                new ObjectParameter("vergiId", vergiId) :
                new ObjectParameter("vergiId", typeof(int));
    
            var kisiNoParameter = kisiNo.HasValue ?
                new ObjectParameter("kisiNo", kisiNo) :
                new ObjectParameter("kisiNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("borcEkle", borcAdiParameter, borcDurumuParameter, borcTutariParameter, borcTarihiParameter, vergiIdParameter, kisiNoParameter);
        }
    
        public virtual int borcGüncelle(Nullable<int> borcNo, string borcAdi, string borcDurumu, Nullable<int> borcTutari, Nullable<System.DateTime> borcTarihi, Nullable<int> vergiId, Nullable<int> kisiNo)
        {
            var borcNoParameter = borcNo.HasValue ?
                new ObjectParameter("borcNo", borcNo) :
                new ObjectParameter("borcNo", typeof(int));
    
            var borcAdiParameter = borcAdi != null ?
                new ObjectParameter("borcAdi", borcAdi) :
                new ObjectParameter("borcAdi", typeof(string));
    
            var borcDurumuParameter = borcDurumu != null ?
                new ObjectParameter("borcDurumu", borcDurumu) :
                new ObjectParameter("borcDurumu", typeof(string));
    
            var borcTutariParameter = borcTutari.HasValue ?
                new ObjectParameter("borcTutari", borcTutari) :
                new ObjectParameter("borcTutari", typeof(int));
    
            var borcTarihiParameter = borcTarihi.HasValue ?
                new ObjectParameter("borcTarihi", borcTarihi) :
                new ObjectParameter("borcTarihi", typeof(System.DateTime));
    
            var vergiIdParameter = vergiId.HasValue ?
                new ObjectParameter("vergiId", vergiId) :
                new ObjectParameter("vergiId", typeof(int));
    
            var kisiNoParameter = kisiNo.HasValue ?
                new ObjectParameter("kisiNo", kisiNo) :
                new ObjectParameter("kisiNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("borcGüncelle", borcNoParameter, borcAdiParameter, borcDurumuParameter, borcTutariParameter, borcTarihiParameter, vergiIdParameter, kisiNoParameter);
        }
    
        public virtual ObjectResult<borcListele_Result> borcListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<borcListele_Result>("borcListele");
        }
    
        public virtual int borcSil(Nullable<int> borcNo)
        {
            var borcNoParameter = borcNo.HasValue ?
                new ObjectParameter("borcNo", borcNo) :
                new ObjectParameter("borcNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("borcSil", borcNoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int vatandasDüzenle(Nullable<int> kisiNo, string tc, string meslek, string adres, string telefon, string mail)
        {
            var kisiNoParameter = kisiNo.HasValue ?
                new ObjectParameter("kisiNo", kisiNo) :
                new ObjectParameter("kisiNo", typeof(int));
    
            var tcParameter = tc != null ?
                new ObjectParameter("tc", tc) :
                new ObjectParameter("tc", typeof(string));
    
            var meslekParameter = meslek != null ?
                new ObjectParameter("meslek", meslek) :
                new ObjectParameter("meslek", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("adres", adres) :
                new ObjectParameter("adres", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("telefon", telefon) :
                new ObjectParameter("telefon", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("mail", mail) :
                new ObjectParameter("mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("vatandasDüzenle", kisiNoParameter, tcParameter, meslekParameter, adresParameter, telefonParameter, mailParameter);
        }
    
        public virtual int vatandasEkle(string tc, string meslek, string adres, string telefon, string mail)
        {
            var tcParameter = tc != null ?
                new ObjectParameter("tc", tc) :
                new ObjectParameter("tc", typeof(string));
    
            var meslekParameter = meslek != null ?
                new ObjectParameter("meslek", meslek) :
                new ObjectParameter("meslek", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("adres", adres) :
                new ObjectParameter("adres", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("telefon", telefon) :
                new ObjectParameter("telefon", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("mail", mail) :
                new ObjectParameter("mail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("vatandasEkle", tcParameter, meslekParameter, adresParameter, telefonParameter, mailParameter);
        }
    
        public virtual ObjectResult<vatandasListe_Result> vatandasListe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vatandasListe_Result>("vatandasListe");
        }
    
        public virtual int vatandasSil(Nullable<int> kisiNo)
        {
            var kisiNoParameter = kisiNo.HasValue ?
                new ObjectParameter("kisiNo", kisiNo) :
                new ObjectParameter("kisiNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("vatandasSil", kisiNoParameter);
        }
    
        public virtual int vergiDüzenle(Nullable<int> vergiId, string vergiAdi, string vergiTipi, Nullable<int> tutar, Nullable<int> faiz, Nullable<int> bakanlikId)
        {
            var vergiIdParameter = vergiId.HasValue ?
                new ObjectParameter("vergiId", vergiId) :
                new ObjectParameter("vergiId", typeof(int));
    
            var vergiAdiParameter = vergiAdi != null ?
                new ObjectParameter("vergiAdi", vergiAdi) :
                new ObjectParameter("vergiAdi", typeof(string));
    
            var vergiTipiParameter = vergiTipi != null ?
                new ObjectParameter("vergiTipi", vergiTipi) :
                new ObjectParameter("vergiTipi", typeof(string));
    
            var tutarParameter = tutar.HasValue ?
                new ObjectParameter("tutar", tutar) :
                new ObjectParameter("tutar", typeof(int));
    
            var faizParameter = faiz.HasValue ?
                new ObjectParameter("faiz", faiz) :
                new ObjectParameter("faiz", typeof(int));
    
            var bakanlikIdParameter = bakanlikId.HasValue ?
                new ObjectParameter("bakanlikId", bakanlikId) :
                new ObjectParameter("bakanlikId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("vergiDüzenle", vergiIdParameter, vergiAdiParameter, vergiTipiParameter, tutarParameter, faizParameter, bakanlikIdParameter);
        }
    
        public virtual int vergiEkle(string vergiAdi, string vergiTipi, Nullable<int> tutar, Nullable<int> faiz, Nullable<int> bakanlikId)
        {
            var vergiAdiParameter = vergiAdi != null ?
                new ObjectParameter("vergiAdi", vergiAdi) :
                new ObjectParameter("vergiAdi", typeof(string));
    
            var vergiTipiParameter = vergiTipi != null ?
                new ObjectParameter("vergiTipi", vergiTipi) :
                new ObjectParameter("vergiTipi", typeof(string));
    
            var tutarParameter = tutar.HasValue ?
                new ObjectParameter("tutar", tutar) :
                new ObjectParameter("tutar", typeof(int));
    
            var faizParameter = faiz.HasValue ?
                new ObjectParameter("faiz", faiz) :
                new ObjectParameter("faiz", typeof(int));
    
            var bakanlikIdParameter = bakanlikId.HasValue ?
                new ObjectParameter("bakanlikId", bakanlikId) :
                new ObjectParameter("bakanlikId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("vergiEkle", vergiAdiParameter, vergiTipiParameter, tutarParameter, faizParameter, bakanlikIdParameter);
        }
    
        public virtual ObjectResult<vergiListe_Result> vergiListe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vergiListe_Result>("vergiListe");
        }
    
        public virtual int vergiSil(Nullable<int> vergiId)
        {
            var vergiIdParameter = vergiId.HasValue ?
                new ObjectParameter("vergiId", vergiId) :
                new ObjectParameter("vergiId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("vergiSil", vergiIdParameter);
        }
    
        public virtual ObjectResult<faizUstüArama_Result> faizUstüArama(Nullable<int> faiz)
        {
            var faizParameter = faiz.HasValue ?
                new ObjectParameter("faiz", faiz) :
                new ObjectParameter("faiz", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<faizUstüArama_Result>("faizUstüArama", faizParameter);
        }
    
        public virtual ObjectResult<tutarUstüArama_Result> tutarUstüArama(Nullable<int> tutar)
        {
            var tutarParameter = tutar.HasValue ?
                new ObjectParameter("tutar", tutar) :
                new ObjectParameter("tutar", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tutarUstüArama_Result>("tutarUstüArama", tutarParameter);
        }
    
        public virtual ObjectResult<vergiTipiArama_Result> vergiTipiArama(string vergiTipi)
        {
            var vergiTipiParameter = vergiTipi != null ?
                new ObjectParameter("vergiTipi", vergiTipi) :
                new ObjectParameter("vergiTipi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vergiTipiArama_Result>("vergiTipiArama", vergiTipiParameter);
        }
    
        public virtual ObjectResult<tutarSecilenAralik_Result> tutarSecilenAralik(Nullable<int> baslangic, Nullable<int> bitis)
        {
            var baslangicParameter = baslangic.HasValue ?
                new ObjectParameter("baslangic", baslangic) :
                new ObjectParameter("baslangic", typeof(int));
    
            var bitisParameter = bitis.HasValue ?
                new ObjectParameter("bitis", bitis) :
                new ObjectParameter("bitis", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tutarSecilenAralik_Result>("tutarSecilenAralik", baslangicParameter, bitisParameter);
        }
    
        public virtual ObjectResult<vergiAdiTipi_Result> vergiAdiTipi(string vergiAdi, string vergiTipi)
        {
            var vergiAdiParameter = vergiAdi != null ?
                new ObjectParameter("vergiAdi", vergiAdi) :
                new ObjectParameter("vergiAdi", typeof(string));
    
            var vergiTipiParameter = vergiTipi != null ?
                new ObjectParameter("vergiTipi", vergiTipi) :
                new ObjectParameter("vergiTipi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vergiAdiTipi_Result>("vergiAdiTipi", vergiAdiParameter, vergiTipiParameter);
        }
    
        public virtual ObjectResult<vergiBakanlik_Result> vergiBakanlik()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vergiBakanlik_Result>("vergiBakanlik");
        }
    
        public virtual ObjectResult<vergiBakanlikBorclar_Result> vergiBakanlikBorclar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vergiBakanlikBorclar_Result>("vergiBakanlikBorclar");
        }
    
        public virtual ObjectResult<vergiVatandasBorcBakanlik_Result> vergiVatandasBorcBakanlik()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vergiVatandasBorcBakanlik_Result>("vergiVatandasBorcBakanlik");
        }
    
        public virtual ObjectResult<string> VergiAdTipTutarFaizTc(string vergiAdi, string vergiTipi, Nullable<int> tutar, Nullable<int> faiz)
        {
            var vergiAdiParameter = vergiAdi != null ?
                new ObjectParameter("vergiAdi", vergiAdi) :
                new ObjectParameter("vergiAdi", typeof(string));
    
            var vergiTipiParameter = vergiTipi != null ?
                new ObjectParameter("vergiTipi", vergiTipi) :
                new ObjectParameter("vergiTipi", typeof(string));
    
            var tutarParameter = tutar.HasValue ?
                new ObjectParameter("tutar", tutar) :
                new ObjectParameter("tutar", typeof(int));
    
            var faizParameter = faiz.HasValue ?
                new ObjectParameter("faiz", faiz) :
                new ObjectParameter("faiz", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VergiAdTipTutarFaizTc", vergiAdiParameter, vergiTipiParameter, tutarParameter, faizParameter);
        }
    
        public virtual ObjectResult<vergiTipiBakanlikAdiMeslek_Result> vergiTipiBakanlikAdiMeslek(string vergiTipi)
        {
            var vergiTipiParameter = vergiTipi != null ?
                new ObjectParameter("vergiTipi", vergiTipi) :
                new ObjectParameter("vergiTipi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vergiTipiBakanlikAdiMeslek_Result>("vergiTipiBakanlikAdiMeslek", vergiTipiParameter);
        }
    
        public virtual ObjectResult<vergiAdiGruplama_Result> vergiAdiGruplama()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vergiAdiGruplama_Result>("vergiAdiGruplama");
        }
    
        public virtual ObjectResult<vergiAdiSiralama_Result> vergiAdiSiralama()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vergiAdiSiralama_Result>("vergiAdiSiralama");
        }
    
        public virtual ObjectResult<vergiTipiGrupla_Result> vergiTipiGrupla()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vergiTipiGrupla_Result>("vergiTipiGrupla");
        }
    
        public virtual ObjectResult<adreIli_Result> adreIli(string adres)
        {
            var adresParameter = adres != null ?
                new ObjectParameter("adres", adres) :
                new ObjectParameter("adres", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<adreIli_Result>("adreIli", adresParameter);
        }
    
        public virtual ObjectResult<meslekBorcDurumBakanlikAd_Result> meslekBorcDurumBakanlikAd()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<meslekBorcDurumBakanlikAd_Result>("meslekBorcDurumBakanlikAd");
        }
    
        public virtual ObjectResult<meslekGrupla_Result> meslekGrupla(string meslek)
        {
            var meslekParameter = meslek != null ?
                new ObjectParameter("meslek", meslek) :
                new ObjectParameter("meslek", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<meslekGrupla_Result>("meslekGrupla", meslekParameter);
        }
    
        public virtual ObjectResult<telefonBaslangiciDokuz_Result> telefonBaslangiciDokuz()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<telefonBaslangiciDokuz_Result>("telefonBaslangiciDokuz");
        }
    
        public virtual ObjectResult<meslekSorgu_Result> meslekSorgu(string meslek)
        {
            var meslekParameter = meslek != null ?
                new ObjectParameter("meslek", meslek) :
                new ObjectParameter("meslek", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<meslekSorgu_Result>("meslekSorgu", meslekParameter);
        }
    
        public virtual ObjectResult<tcBasDokuzBitBes_Result> tcBasDokuzBitBes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tcBasDokuzBitBes_Result>("tcBasDokuzBitBes");
        }
    
        public virtual ObjectResult<kisiNoTcAdresBorcAdTutar_Result> kisiNoTcAdresBorcAdTutar(Nullable<int> kisiNo)
        {
            var kisiNoParameter = kisiNo.HasValue ?
                new ObjectParameter("kisiNo", kisiNo) :
                new ObjectParameter("kisiNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<kisiNoTcAdresBorcAdTutar_Result>("kisiNoTcAdresBorcAdTutar", kisiNoParameter);
        }
    
        public virtual ObjectResult<bakanlikAdCirVerTütarBorcAdiVatMeslek_Result> bakanlikAdCirVerTütarBorcAdiVatMeslek(string bakanlikAdi)
        {
            var bakanlikAdiParameter = bakanlikAdi != null ?
                new ObjectParameter("bakanlikAdi", bakanlikAdi) :
                new ObjectParameter("bakanlikAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bakanlikAdCirVerTütarBorcAdiVatMeslek_Result>("bakanlikAdCirVerTütarBorcAdiVatMeslek", bakanlikAdiParameter);
        }
    
        public virtual ObjectResult<bakanlikAdSorgu_Result> bakanlikAdSorgu(string bakanlikAd)
        {
            var bakanlikAdParameter = bakanlikAd != null ?
                new ObjectParameter("bakanlikAd", bakanlikAd) :
                new ObjectParameter("bakanlikAd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bakanlikAdSorgu_Result>("bakanlikAdSorgu", bakanlikAdParameter);
        }
    
        public virtual ObjectResult<bakDaireBaskSorgu_Result> bakDaireBaskSorgu(string daireBask)
        {
            var daireBaskParameter = daireBask != null ?
                new ObjectParameter("daireBask", daireBask) :
                new ObjectParameter("daireBask", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bakDaireBaskSorgu_Result>("bakDaireBaskSorgu", daireBaskParameter);
        }
    
        public virtual ObjectResult<ciroVerAdiBorcTutar_Result> ciroVerAdiBorcTutar(Nullable<int> miniCiro, Nullable<int> maxiCiro)
        {
            var miniCiroParameter = miniCiro.HasValue ?
                new ObjectParameter("miniCiro", miniCiro) :
                new ObjectParameter("miniCiro", typeof(int));
    
            var maxiCiroParameter = maxiCiro.HasValue ?
                new ObjectParameter("maxiCiro", maxiCiro) :
                new ObjectParameter("maxiCiro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ciroVerAdiBorcTutar_Result>("ciroVerAdiBorcTutar", miniCiroParameter, maxiCiroParameter);
        }
    
        public virtual ObjectResult<ciroBakAdDaireBsk_Result> ciroBakAdDaireBsk(Nullable<int> miniCiro, Nullable<int> maxiCiro)
        {
            var miniCiroParameter = miniCiro.HasValue ?
                new ObjectParameter("miniCiro", miniCiro) :
                new ObjectParameter("miniCiro", typeof(int));
    
            var maxiCiroParameter = maxiCiro.HasValue ?
                new ObjectParameter("maxiCiro", maxiCiro) :
                new ObjectParameter("maxiCiro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ciroBakAdDaireBsk_Result>("ciroBakAdDaireBsk", miniCiroParameter, maxiCiroParameter);
        }
    
        public virtual ObjectResult<bakAdCiroVerAdTipBorcAdTarihVatMeslTel_Result> bakAdCiroVerAdTipBorcAdTarihVatMeslTel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bakAdCiroVerAdTipBorcAdTarihVatMeslTel_Result>("bakAdCiroVerAdTipBorcAdTarihVatMeslTel");
        }
    
        public virtual ObjectResult<siralaBakanlikAd_Result> siralaBakanlikAd()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<siralaBakanlikAd_Result>("siralaBakanlikAd");
        }
    
        public virtual ObjectResult<siralaBakanlikAdTers_Result> siralaBakanlikAdTers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<siralaBakanlikAdTers_Result>("siralaBakanlikAdTers");
        }
    
        public virtual ObjectResult<secilenIkiTarihim_Result> secilenIkiTarihim(Nullable<System.DateTime> basTarih, Nullable<System.DateTime> bitTarih)
        {
            var basTarihParameter = basTarih.HasValue ?
                new ObjectParameter("basTarih", basTarih) :
                new ObjectParameter("basTarih", typeof(System.DateTime));
    
            var bitTarihParameter = bitTarih.HasValue ?
                new ObjectParameter("bitTarih", bitTarih) :
                new ObjectParameter("bitTarih", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<secilenIkiTarihim_Result>("secilenIkiTarihim", basTarihParameter, bitTarihParameter);
        }
    
        public virtual ObjectResult<borcGirilenDegerAralik_Result> borcGirilenDegerAralik(Nullable<int> minimumTutar, Nullable<int> maksimumTutar)
        {
            var minimumTutarParameter = minimumTutar.HasValue ?
                new ObjectParameter("minimumTutar", minimumTutar) :
                new ObjectParameter("minimumTutar", typeof(int));
    
            var maksimumTutarParameter = maksimumTutar.HasValue ?
                new ObjectParameter("maksimumTutar", maksimumTutar) :
                new ObjectParameter("maksimumTutar", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<borcGirilenDegerAralik_Result>("borcGirilenDegerAralik", minimumTutarParameter, maksimumTutarParameter);
        }
    }
}
